### ISSUE TITLE
Missing a helper function to create validators from predicates

### ISSUE THREAD

**Issue by DanielCardonaRojas** [stoeffel/elm-verify#20]
It would be nice to have a shorthand for creating a validator from a predicate and an error.

This what I'm using in my project currently:

```elm
withPredicate : (a -> Bool) -> e -> Validator e a a
withPredicate pred e = 
    \a ->
        if pred a then a |> Verify.ok a else a |> Verify.fail e
```

Would a pull request be accepted for this?

**Comment by stoeffel** [comment]
Do you have an example where you'd want to use this? There is http://package.elm-lang.org/packages/stoeffel/elm-verify/4.0.0/Verify#fromMaybe could be helpful for your usecase.

**Comment by DanielCardonaRojas** [comment]
At the time I posted this issue I was still on 3.0 fromMaybe can definitely get the job done. Thanks!
