### ISSUE TITLE
using a non empty list for errors.

### ISSUE THREAD

**Issue by stoeffel** [stoeffel/elm-verify#21]
I was wondering if it would be a good idea to ensure that there is always at least one error by using a non-empty list. I like using `(a, List a)` for that to avoid depending on a package. 

```diff
type alias Validator error input verified = 
-    input -> Result (List error) verified
type alias Validator error input verified = 
+    input -> Result (a, List error) verified
```

**Comment by stoeffel** [comment]
in addition we could return a non-empty list from `notEmpty` as well.

```elm
{-| Fails if a List is empty.

    notEmpty "error" []
    --> Err [ "error" ]

    notEmpty "error" [1]
    --> Ok ( 1, [] )

-}
notEmpty : error -> Validator error (List a) ( a, List a )
notEmpty error input =
    case input of
        [] ->
            Err [ error ]

        head :: tail ->
            Ok ( head, tail )
```

**Comment by stoeffel** [comment]
thoughts @michaeljones @gyzerok?

**Comment by michaeljones** [comment]
I haven't had to use non-empty lists all that much so I don't have a clear vision for when but it seems useful :) I suspect some people might like a nonEmpty that still returns a normal list? But I guess they are just one `::` away from putting the head back on the tail to get a normal list anyway? 

I can see cases where converting to `(a, List a)` is super useful as the downstream code doesn't want to have to deal with the empty case but I tend to use Verify just ahead of doing Json encoding so this would  be less useful in that case as I might want to make sure a list is empty but then I would just want to call `Json.Encode.list` on the result.

But, yeah, I'd still include it.

**Comment by gyzerok** [comment]
Recently I was playing around with the implementation of `Verify.List.each`/`Verify.List.every`. One thing which made implementation annoying was handling impossible case with the empty list inside error.

Nice to see, that you reached the same idea entirely separately. Looks like this change indeed is needed? 😄 

There is however one more thing which is a bit connected. Richard in his `elm-validate` library recently switched from type aliases for validators to opaque types. This provides power to change internal implementations in whatever way, without introducing breaking changes.

With opaque type we could instead have 2 functions for validator execution - one would return list of errors, another returns first error.

To conclude - I definitely support the change. Just wanted to bring some more things to the table before going forward, so we have less breaking changes. What do you think?

**Comment by stoeffel** [comment]
re: opaque type for this package.

I've actually tried this (with @jwoudenberg ) in our codebase before it transformed into this package and it was a bit of a pain, because you end up adding all the functions from `Result` to this module and the api surface grows a lot. I like having a small api and using tools people already know. That's also why I would choose `(a, List a)` over an `EmptyList` module. I'm not saying that I'm against opaque types, I actually love it when it makes sense, but I think we would loose all the composability that comes from just returning a result. I'm happy to revisit that though if someone wants to makes a nice api proposal.

**Comment by gyzerok** [comment]
I am wondering if it’s okay to continue opaque types discussion here or create a new issue?

I am not entirely follow how API surface are would grow with opaque types. Can you share some examples maybe?
