### ISSUE TITLE
Parallel composition of Validators

### ISSUE THREAD

**Issue by DanielCardonaRojas** [stoeffel/elm-verify#23]
Currently its tricky to compose validators in a parallel fashion, the idea is kind to an arrow type combinator like split (Haskells (&&&) in Control.Arrow) to apply both validators to the same input and then disambiguate which result to pic with a merging function.

I actually had to create this for a project I'm working on, here are two different ways of writing this function:

```elm
parallel : (a -> b -> c) -> Validator e i a -> Validator e i b -> Validator e i c
parallel merge v1 v2 = 
    \a -> 
        case (v1 a, v2 a) of
            (Ok r1, Ok r2) ->
                Ok <| merge r1 r2
            (Err e1, Err e2) ->
                Err (e1 ++ e2)
            (Err e, _) ->
                Err e
            (_, Err e) ->
                Err e

parallel_ : (a -> b -> c) -> Validator e i a -> Validator e i b -> Validator e i c
parallel_ merge v1 v2 = 
    let 
        map f validator = \i -> validator i |> Result.map f
    in
        map merge v1 
        |> Verify.custom v2
```

**Comment by stoeffel** [comment]
Hi @DanielCardonaRojas !

I think you can do this with the current api already https://ellie-app.com/Hds2JsRLvSa1


```elm
notBlankAndMinLength : Validator String String String
notBlankAndMinLength =
    validate (\a b -> a ++ b)
        -- <== merge
        |> verify identity (String.Verify.notBlank "blank")
        |> verify identity (String.Verify.minLength 3 "min 3 chars")
```

**Comment by DanielCardonaRojas** [comment]
Yeah I think your right It wasn't obvious at first. I tried it out with a password confirmation example continuing from yours:

https://ellie-app.com/HgTTXktntma1

**Comment by stoeffel** [comment]
nice!
