### ISSUE TITLE
Consider creating 'validate' alias to mirror Json.Decode.Pipeline.decode

### ISSUE THREAD

**Issue by michaeljones** [stoeffel/elm-verify#5]
The library current uses `Verify.ok` to start a validation chain. It might be more readable as an alias called `Verify.validate` which would mirror the `Json.Decode.Pipeline.decode` function which itself a more readable alias of `Json.Decode.succeed`.

**Comment by stoeffel** [comment]
yes, I think this is a good idea. wanna make a pr?

**Comment by michaeljones** [comment]
Great, I've tried at #9. Hope it is suitable. Happy to make changes.

**Comment by michaeljones** [comment]
Closing as #9 has been merged.
