### ISSUE TITLE
Adjust definition of Verify.andThen

### ISSUE THREAD

**Issue by michaeljones** [stoeffel/elm-verify#7]
Not 100% sure of this one as I don't have everything compiling on my side yet but from my experience with `Json.Decode` I expected `Verify.andThen` to work like this:

```elm
andThen : (a -> Validator error input b) -> Validator error input a -> Validator error input b
andThen func validator =
    \input ->
        let
            result =
                validator input
        in
        result
            |> Result.andThen (flip func input)
```
Then the signature matches what I would expect. The implementation can be condensed a bit. 

Again, not 100% sure as my wider program doesn't compile yet but this matches my expectations a bit closer.

**Comment by michaeljones** [comment]
I suspect I'm being too rigid with structuring my code like I would in a Json.Decode scenario. I'll try to explore the current set up a bit more before claiming that things should change! Thanks for the project though. Just got it all compiling with a fairly complicated data structure. Looks hopeful :)

**Comment by michaeljones** [comment]
I've attempted to go back through a try to adjust my use of the library but I'm getting stuck. Here is my validation of a nested data structure:

```elm
activityValidator : List AD.ActivityTypeDefinition -> Validator EditableActivity ActivityUploadData
activityValidator activityTypeDefinitions =
    let
        validator : AD.ActivityTypeName -> Validator EditableActivity AD.ActivityType
        validator type_ =
            case type_ of
                AD.ReportActivityName ->
                    V.ok AD.ReportActivityOptions
                        |> V.keep (.options >> .completion)
                        |> V.keep (.options >> .unitListTypes)
                        |> V.keep (.options >> .targetUnitTypeId)
                        |> verifyMap AD.ReportActivity

                AD.FormActivityName ->
                    V.ok AD.FormActivityOptions
                        |> V.keep (.options >> .formType)
                        |> V.keep (.options >> .generateTimelineNote)
                        |> V.keep (.options >> .manualBlock)
                        |> verifyMap AD.FormActivity

        activityTypeValidator : Validator EditableActivity AD.ActivityType
        activityTypeValidator =
            verifyField .type_
                |> verifyAndThen validator

        activityTypeIdValidator : Validator EditableActivity AD.ActivityTypeId
        activityTypeIdValidator { type_ } =
            case AD.findActivityTypeId type_ activityTypeDefinitions of
                Nothing ->
                    Err [ "Failed to find activity type id" ]

                Just activityTypeDefinition ->
                    Ok activityTypeDefinition.id
    in
    V.ok ActivityUploadData
        |> V.keep .id
        |> V.keep .name
        |> V.custom activityTypeIdValidator  -- gets the activity type id from the activity type
        |> V.verify identity activityTypeValidator -- gets all the activity options from the activity type


verifyMap : (a -> b) -> V.Validator error input a -> V.Validator error input b
verifyMap func validator =
    validator >> Result.map func


verifyAndThen : (a -> V.Validator error input b) -> V.Validator error input a -> V.Validator error input b
verifyAndThen func validator =
    \input ->
        let
            result =
                validator input
        in
        result
            |> Result.andThen (flip func input)


verifyField : (bigger -> smaller) -> V.Validator error bigger smaller
verifyField func =
    func >> Ok
```

I've found the `Verify.custom` works great for the `activityTypeIdValidator` which is directly returning a `Result` but for the `activityTypeValidator` beneath it which wants to run further validations on the nested data, I'm having to do some awkward things. Probably because I'm missing something and just wanting to do what I do with the `Decode.Pipeline`. It is further complicated by wanting the value of the `type_` field to understand how to validate the nested section.

You can see how hard I'm trying to force it into the `Decode` mold by the introduction of the `verifyField` function. I'm hoping it is all unnecessary.

I'd love some help understanding how best to approach this.

**Comment by stoeffel** [comment]
I think you can do the following. Sorry, it's a bit hard without being able to compile this. (btw `error` is missing from the type signatures)

```elm
activityValidator : List AD.ActivityTypeDefinition -> Validator error EditableActivity ActivityUploadData
activityValidator activityTypeDefinitions =
    let
        validator : AD.ActivityTypeName -> Validator error EditableActivity AD.ActivityType
        validator type_ =
            case type_ of
                AD.ReportActivityName ->
                    V.ok (Ad.ReportActivity << AD.ReportActivityOptions) -- no need for Verify.map. I think this is cleaner
                        |> V.keep (.options >> .completion)
                        |> V.keep (.options >> .unitListTypes)
                        |> V.keep (.options >> .targetUnitTypeId)

                AD.FormActivityName ->
                    V.ok (Ad.FormActivity << AD.FormActivityOptions)
                        |> V.keep (.options >> .formType)
                        |> V.keep (.options >> .generateTimelineNote)
                        |> V.keep (.options >> .manualBlock)

        activityTypeValidator : Validator error EditableActivity AD.ActivityType
        activityTypeValidator data =
                validator data.type_ data -- less api to learn. I think it's better to learn the nature of `Validator`

        activityTypeIdValidator : Validator error AD.ActivityTypeName AD.ActivityTypeId
        activityTypeIdValidator =
            -- you can use fromMaybe here
            V.fromMaybe (\type_ -> AD.findActivityTypeId type_ activityTypeDefinitions) "Failed to find activity type id"
    in
    V.ok ActivityUploadData
        |> V.keep .id
        |> V.keep .name
        |> V.verify .type_ activityTypeIdValidator  -- narrowing the validators type signature with verify, helps understanding what's going on from the caller side
        |> V.custom activityTypeValidator -- gets all the activity options from the activity type
```

**Comment by michaeljones** [comment]
Thank you so much for taking the time to do that. I should have realised that without the compiler to help it becomes a more complex task. I appreciate the guidance.

I definitely need to learn to respect the types more instead of just trying to blindly apply familiar patterns. I can see why this all works. I guess it doesn't need as much indirection as a Decode example as there isn't an actual decoding step, the data is already there to be inspected and used. 

Whilst I appreciate the elegance of `(AD.FormActivity << AD.FormActivityOptions)` as an approach, it doesn't seem to work when there is more than one field in `FormActivityOptions`. Which would have been clearer if I had provided a working/compilable example! So I'm still using `verifyMap` for the moment. Perhaps there is a still a more elegant approach.

**Comment by stoeffel** [comment]
Oops. You are right `<<` in `ok` is not what you want, but you can just compose with `Result.map Foo`. checkout this ellie https://ellie-app.com/nWdpsNH86a1/1.
An example for this would be nice in the docs. I prefer doing this over adding it to the lib, because it's more explicit and it shows that `Validator` can be composed with any functions that works with `Result`.

**Comment by michaeljones** [comment]
I think I still want a pretty API but if I was less focussed on that I might have a better understanding of all this, so yeah, cool, I work with that. Thanks again for all the help & the library.
