### ISSUE TITLE
convenience function to verify all items in a list/dict/array/set

### ISSUE THREAD

**Issue by stoeffel** [stoeffel/elm-verify#8]
example https://ellie-app.com/rXBsnHztMa1/0

### Open questions:

should we report all errors or only the first?
should there be a function to get all errors and one for getting the first?
should we add the index/key to the error message `(Int, error)`?
should we add specific functions to TYPE.Verify? yes

naming `all`, `items`, `elements`, `values`?

**Comment by kornicameister** [comment]
@stoeffel I recently stumbled upon such a use case, would be great to have that in the library.
